# Generated by Django 2.2.12 on 2020-05-21 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('4caadb1c-38bf-41b3-aea7-761c36fb53ef'), editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
