# Generated by Django 2.2.12 on 2020-05-21 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200521_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('45858054-6092-4f30-9f89-df0bb5072276'), editable=False),
        ),
    ]
