# Generated by Django 2.2.12 on 2020-05-21 01:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200521_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('4bc59dae-5f73-4f16-bff6-a73d2b16b0dc'), editable=False),
        ),
    ]
