# Generated by Django 2.2.12 on 2020-05-21 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200521_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('0da25096-e52a-443d-ad6c-7c44f2bd4eb7'), editable=False),
        ),
    ]
