# Generated by Django 2.2.12 on 2020-05-15 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ip', models.TextField()),
                ('port', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('type', models.TextField(choices=[('socks5', 'socks5'), ('https', 'https')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
