# Generated by Django 2.2.12 on 2020-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_auto_20200518_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='type',
            field=models.CharField(choices=[('socks5', 'socks5'), ('https', 'https')], max_length=255),
        ),
    ]
