# Generated by Django 2.2.12 on 2020-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
