# Generated by Django 2.2.12 on 2020-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_users', '0002_auto_20200518_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='vk_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vkusersgroup',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
