# Generated by Django 2.2.12 on 2020-05-19 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vk_users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_users', '0003_auto_20200518_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkFileUsers',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=vk_users.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
