# Generated by Django 2.2.12 on 2020-05-18 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_akk', '0005_auto_20200518_2138'),
        ('vk_users', '0003_auto_20200518_1902'),
        ('tasks', '0002_auto_20200518_2234'),
    ]

    # operations = [
    #     # migrations.CreateModel(
    #     #     name='FollowTask',
    #     #     fields=[
    #     #         ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
    #     #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
    #     #         ('vk_akks_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_akk.VkAkksGroup')),
    #     #         ('vk_users_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_users.VkUsersGroup')),
    #     #     ],
    #     # ),
    #     migrations.DeleteModel(name='FollowTask'),
    #     migrations.DeleteModel(
    #         name='ActionTask',
    #     ),
    # ]
