# Generated by Django 2.2.12 on 2020-05-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200518_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='followtask',
            name='follow_number',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
