# Generated by Django 2.2.12 on 2020-05-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_followtask_follow_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='akkfollowtask',
            name='follow_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.FollowTask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followtask',
            name='status',
            field=models.TextField(choices=[('NEW', 'NEW'), ('READY_TO_START', 'READY_TO_START'), ('ACTIVE', 'ACTIVE'), ('COMPLETE', 'COMPLETE')], default='NEW'),
        ),
    ]
