# Generated by Django 2.2.12 on 2020-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200519_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='followtask',
            name='is_fast_follow',
            field=models.BooleanField(default=False),
        ),
    ]
