# Generated by Django 2.2.12 on 2020-05-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_akk', '0003_auto_20200518_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='user_agent',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='vkakk',
            name='login',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='vkakk',
            name='vk_user_id',
            field=models.TextField(default='-1'),
        ),
    ]
