# Generated by Django 2.2.12 on 2020-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_akk', '0004_auto_20200518_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkakksgroup',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
