# Generated by Django 2.2.12 on 2020-05-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_akk', '0005_auto_20200518_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkakk',
            name='vk_last_auth_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vkakk',
            name='vk_url',
            field=models.URLField(null=True),
        ),
    ]
